// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1alpha1/dlock.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockEvent int32

const (
	LockEvent_Acquired LockEvent = 0
	LockEvent_Failed   LockEvent = 1
)

// Enum value maps for LockEvent.
var (
	LockEvent_name = map[int32]string{
		0: "Acquired",
		1: "Failed",
	}
	LockEvent_value = map[string]int32{
		"Acquired": 0,
		"Failed":   1,
	}
)

func (x LockEvent) Enum() *LockEvent {
	p := new(LockEvent)
	*p = x
	return p
}

func (x LockEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1alpha1_dlock_proto_enumTypes[0].Descriptor()
}

func (LockEvent) Type() protoreflect.EnumType {
	return &file_api_v1alpha1_dlock_proto_enumTypes[0]
}

func (x LockEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockEvent.Descriptor instead.
func (LockEvent) EnumDescriptor() ([]byte, []int) {
	return file_api_v1alpha1_dlock_proto_rawDescGZIP(), []int{0}
}

type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TryLock       bool                   `protobuf:"varint,2,opt,name=tryLock,proto3" json:"tryLock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_api_v1alpha1_dlock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_dlock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_dlock_proto_rawDescGZIP(), []int{0}
}

func (x *LockRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LockRequest) GetTryLock() bool {
	if x != nil {
		return x.TryLock
	}
	return false
}

type LockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         LockEvent              `protobuf:"varint,1,opt,name=event,proto3,enum=dlock.LockEvent" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_api_v1alpha1_dlock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_dlock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_dlock_proto_rawDescGZIP(), []int{1}
}

func (x *LockResponse) GetEvent() LockEvent {
	if x != nil {
		return x.Event
	}
	return LockEvent_Acquired
}

var File_api_v1alpha1_dlock_proto protoreflect.FileDescriptor

const file_api_v1alpha1_dlock_proto_rawDesc = "" +
	"\n" +
	"\x18api/v1alpha1/dlock.proto\x12\x05dlock\x1a\x1bgoogle/protobuf/empty.proto\"9\n" +
	"\vLockRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\atryLock\x18\x02 \x01(\bR\atryLock\"6\n" +
	"\fLockResponse\x12&\n" +
	"\x05event\x18\x01 \x01(\x0e2\x10.dlock.LockEventR\x05event*%\n" +
	"\tLockEvent\x12\f\n" +
	"\bAcquired\x10\x00\x12\n" +
	"\n" +
	"\x06Failed\x10\x012<\n" +
	"\x05Dlock\x123\n" +
	"\x04Lock\x12\x12.dlock.LockRequest\x1a\x13.dlock.LockResponse\"\x000\x01B0Z.github.com/alexandreLamarre/dlock/api/v1alpha1b\x06proto3"

var (
	file_api_v1alpha1_dlock_proto_rawDescOnce sync.Once
	file_api_v1alpha1_dlock_proto_rawDescData []byte
)

func file_api_v1alpha1_dlock_proto_rawDescGZIP() []byte {
	file_api_v1alpha1_dlock_proto_rawDescOnce.Do(func() {
		file_api_v1alpha1_dlock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1alpha1_dlock_proto_rawDesc), len(file_api_v1alpha1_dlock_proto_rawDesc)))
	})
	return file_api_v1alpha1_dlock_proto_rawDescData
}

var file_api_v1alpha1_dlock_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1alpha1_dlock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1alpha1_dlock_proto_goTypes = []any{
	(LockEvent)(0),       // 0: dlock.LockEvent
	(*LockRequest)(nil),  // 1: dlock.LockRequest
	(*LockResponse)(nil), // 2: dlock.LockResponse
}
var file_api_v1alpha1_dlock_proto_depIdxs = []int32{
	0, // 0: dlock.LockResponse.event:type_name -> dlock.LockEvent
	1, // 1: dlock.Dlock.Lock:input_type -> dlock.LockRequest
	2, // 2: dlock.Dlock.Lock:output_type -> dlock.LockResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1alpha1_dlock_proto_init() }
func file_api_v1alpha1_dlock_proto_init() {
	if File_api_v1alpha1_dlock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1alpha1_dlock_proto_rawDesc), len(file_api_v1alpha1_dlock_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1alpha1_dlock_proto_goTypes,
		DependencyIndexes: file_api_v1alpha1_dlock_proto_depIdxs,
		EnumInfos:         file_api_v1alpha1_dlock_proto_enumTypes,
		MessageInfos:      file_api_v1alpha1_dlock_proto_msgTypes,
	}.Build()
	File_api_v1alpha1_dlock_proto = out.File
	file_api_v1alpha1_dlock_proto_goTypes = nil
	file_api_v1alpha1_dlock_proto_depIdxs = nil
}
