// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/v1alpha1/dlock.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dlock_Lock_FullMethodName = "/dlock.Dlock/Lock"
)

// DlockClient is the client API for Dlock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DlockClient interface {
	Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LockResponse], error)
}

type dlockClient struct {
	cc grpc.ClientConnInterface
}

func NewDlockClient(cc grpc.ClientConnInterface) DlockClient {
	return &dlockClient{cc}
}

func (c *dlockClient) Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LockResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Dlock_ServiceDesc.Streams[0], Dlock_Lock_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LockRequest, LockResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dlock_LockClient = grpc.ServerStreamingClient[LockResponse]

// DlockServer is the server API for Dlock service.
// All implementations should embed UnimplementedDlockServer
// for forward compatibility.
type DlockServer interface {
	Lock(*LockRequest, grpc.ServerStreamingServer[LockResponse]) error
}

// UnimplementedDlockServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDlockServer struct{}

func (UnimplementedDlockServer) Lock(*LockRequest, grpc.ServerStreamingServer[LockResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (UnimplementedDlockServer) testEmbeddedByValue() {}

// UnsafeDlockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DlockServer will
// result in compilation errors.
type UnsafeDlockServer interface {
	mustEmbedUnimplementedDlockServer()
}

func RegisterDlockServer(s grpc.ServiceRegistrar, srv DlockServer) {
	// If the following call pancis, it indicates UnimplementedDlockServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dlock_ServiceDesc, srv)
}

func _Dlock_Lock_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DlockServer).Lock(m, &grpc.GenericServerStream[LockRequest, LockResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dlock_LockServer = grpc.ServerStreamingServer[LockResponse]

// Dlock_ServiceDesc is the grpc.ServiceDesc for Dlock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dlock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dlock.Dlock",
	HandlerType: (*DlockServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Lock",
			Handler:       _Dlock_Lock_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1alpha1/dlock.proto",
}
