name: Lint
on:
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '*.md'
    - '.gitignore'
    - 'CODEOWNERS'
    - 'LICENSE'

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@27fdb267c15a8835f1ead03dfa07f89be2bb741a
        with:
          go-version-file: .tool-versions
      - uses: golangci/golangci-lint-action@b7bcab6379029e905e3f389a6bf301f1bc220662
        with:
          version-file: .tool-versions
          args: --timeout=10m